language: php

php:
  - 7.4
  - 8.0
  - 8.1

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

cache:
  directories:
    - $HOME/.composer

install:
  - composer update ${PREFER_LOWEST}

before_script:
  - echo "xdebug.mode=coverage" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer test

notifications:
  email: false

branches:
  only:
    - master
